### ISSUE TITLE
AWSに登録したDeguを全て確認したい

### ISSUE THREAD

**Issue by DeguUser** [open-degu/USER_COMMUNITY#1]
AWSに登録したDeguを一覧表示する方法はありますか?

**Comment by ohsawa** [comment]
AWS IoTのコンソールにログインして、左のメニューから "管理"->"モノ" をクリックし、
「モノの検索」に ”Degu” を入力すると登録されたDeguが一覧表示されます。

**Comment by DeguUser** [comment]
表示されました。
