### ISSUE TITLE
Thread通信について

### ISSUE THREAD

**Issue by hanakooota** [open-degu/USER_COMMUNITY#10]
現在、以下のものを購入し、Deguユーザマニュアル(https://open-degu.github.io/user_manual)にならって、接続確認を行っております。

・Armadillo-IoT G3
・Threadアドオンモジュール(OP-AGA-TH00-00)を上記に装着
・Deguベースユニット
・Deguスタータキット

手順通りに実施し、一部うまく行かずに困っております。
Deguコンソールから1命令ずつ動作させると、request_postメソッド後の、request_getメソッドが失敗している様でした。

● 質問1
DeguベースユニットとGW間が、接続出来ているか否かを確認する方法を教えてください。

● 質問2
Threadアドオンモジュールの記載があるマニュアルは、どの様に入手できますか。

**Comment by takumiando** [comment]
>DeguベースユニットとGW間が、接続出来ているか否かを確認する方法を教えてください。

基本的には、デフォルトの`main.py`で確認できるようになっています。`request_get`に成功すると、`Deguゲートウェイからデバイスシャドウを取得できた`ということなので、LED1を点灯し、これを示しています。

うまくいかない場合は、Deguゲートウェイでのコマンド操作にて状態を確認することができます。

Deguゲートウェイで、次のコマンドを実行していただけますか?
```
# wpanctl getprop
```

Deguが正しくThreadネットワークに接続できている場合、次のように表示されます。

```
Thread:ChildTable = [
        "E656AF728B7811A0, RLOC16:a40d, NetDataVer:85, LQIn:3, AveRssi:-71, LastRssi:-73, Timeout:240, Age:12, RxOnIdle:yes, FTD:no, SecDataReq:yes, FullNetData:no"
]
Thread:ChildTable:Addresses = [
        "E656AF728B7811A0, RLOC16:a40d, IPv6Addrs:[fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5]"
]
```

`Thread:ChildTable`は、Deguゲートウェイに接続されているDegu(正確には、[MTD: Minimal Thread Device](https://openthread.io/guides/thread-primer/node-roles-and-types) として動作しているデバイス)の一覧です。

`Thread:ChildTable:Addresses`は、それらに対して割り当てられたIPV6アドレスの一覧です。

もし同様の表示がある場合、`ping6`でそれぞれのDeguに対して疎通確認することができるはずです。

```
# ping6 -I wpan0 fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5
PING fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5(fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5) from fd82:54e9:c4e8::1 wpan0: 56 data bytes
64 bytes from fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5: icmp_seq=1 ttl=64 time=15.0 ms
64 bytes from fd82:54e9:c4e8:0:7b0b:3402:44f4:21b5: icmp_seq=2 ttl=64 time=14.9 ms
...
```

>Threadアドオンモジュールの記載があるマニュアルは、どの様に入手できますか。

申し訳ありません、Threadアドオンモジュールそのものに関するドキュメントは現在提供できておりません。今後、製品マニュアルにて掲載予定です。
具体的に、どのようなことを確認したいか教えていただけますか?

**Comment by hanakooota** [comment]
コメントありがとうございます。
● 質問1
wpanctl getprop コマンドを実行したところ、以下のような結果が得られました。

Thread:ChildTable = [
        "9239C7DC41B73107, RLOC16:1c01, NetDataVer:233, LQIn:3, AveRssi:-60, LastRssi:-59, Timeout:240, Age:90, RxOnIdle:yes, FTD:no, SecDataReq:yes, FullNetData:no"
]
Thread:ChildTable:Addresses = [
        "9239C7DC41B73107, RLOC16:1c01, IPv6Addrs:[fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1]"
]
Thread:ChildTimeout = 240
Thread:DeviceMode = 0x0F
Thread:Leader:Address = "fdac:2d44:7c63::ff:fe00:1c00"
Thread:Leader:LocalWeight = 0x40
Thread:Leader:NetworkData = [08040B02BF23]
Thread:Leader:RouterID = 0x07
Thread:Leader:StableNetworkData = []
Thread:Leader:Weight = 0x40
Thread:NeighborTable = [
        "9239C7DC41B73107, RLOC16:1c01, LQIn:3, AveRssi:-60, LastRssi:-59, Age:90, LinkFC:5000, MleFC:5010, IsChild:yes, RxOnIdle:yes, FTD:no, SecDataReq:yes, FullNetData:no"
]
Thread:NeighborTable:ErrorRates = [
        "9239C7DC41B73107, RLOC16:1c01, FrameErrRate:0.00%, MsgErrorRate:0.00%, AveRssi:-60, LastRssi:-59, "
]
Thread:NetworkData: <empty> (16)
Thread:NetworkDataVersion = 0x1C
Thread:OffMeshRoutes = []
Thread:OnMeshPrefixes = []
Thread:Parent: <empty> (15335444)
Thread:PendingDataset = []
Thread:RLOC16 = 0x1C00
Thread:RouterDowngradeThreshold = 0x17
Thread:RouterID = 0x07
Thread:RouterTable = [
        "0EAA72A42D886EDB, RLOC16:1c00, RouterId:7, NextHop:63, PathCost:0, LQIn:0, LQOut:0, Age:0, LinkEst:no"
]
Thread:RouterUpgradeThreshold = 0x10
Thread:StableNetworkData: <empty> (16)
Thread:StableNetworkDataVersion = 0xE9
com.nestlabs.internal:Network:AllowingJoin = false
com.nestlabs.internal:Network:PassthruPort = 0x1634

上記結果が得られたため、ping6コマンドを実行してみました。
すると・・・。
# ping6 -I wpan0 fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1
PING fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1(fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1) from fdac:2d44:7c63::1 wpan0: 56 data bytes
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=1 ttl=64 time=14.6 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=2 ttl=64 time=14.8 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=3 ttl=64 time=18.0 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=4 ttl=64 time=14.5 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=5 ttl=64 time=20.8 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=6 ttl=64 time=17.6 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=7 ttl=64 time=23.5 ms
64 bytes from fdac:2d44:7c63:0:6e4d:da7:a0ac:f4b1: icmp_seq=8 ttl=64 time=16.1 ms

上記の通り、pingに応える様です。

物理的には接続出来ていることを確認できましたが、
Issue #11にある通り、"Deguが送信したJSONメッセージがモノのシャドウに反映されません"と
同じ状況だということが分かりました。
こちらの、回答を暫く待ってみようと思います。

● 質問2
OSが正しく認識出来ているかを確認するために、スペシャルデバイス名が知りたかっただけです。
今は、物理的に接続状態出来ていることを確認出来たため、Issue #11の回答を待とうと思います。

**Comment by takumiando** [comment]
ご確認ありがとうございます。

>物理的には接続出来ていることを確認できましたが、
>Issue #11にある通り、"Deguが送信したJSONメッセージがモノのシャドウに反映されません"と
>同じ状況だということが分かりました。

では、お使いのDeguはAWSに(MACアドレスを名前として)登録されているが、Shadowが更新されない、という状況で合っていますでしょうか?

Deguの電源を入れ直しても、状況は変わりませんか?

**Comment by hanakooota** [comment]
はい。電源入れなおしても状況が変わりませんでした。
当方で色々調べてみたところ、ゲートウェイからAWSへの接続要求が
発行されていますが、その応答がないところが確認できました。
社内N/Wのセキュリティポリシ上、その接続を許可していないことが
原因の様でした。
＃ アウトバンドの8883ポート接続は禁止されていました。

社内N/W以外の回線に接続したところ、シャドウが更新されることを
確認しました。
社内N/Wのセキュリティポリシ変更が必要になりますが、
その際アウトバンドの8883接続のみ許可変更し、その他の設定変更は
不要でしょうか。

**Comment by takumiando** [comment]
ご確認ありがとうございます。

>社内N/Wのセキュリティポリシ上、その接続を許可していないことが
>原因の様でした。

このような環境での使用についてマニュアルに記載されていませんね、申し訳ありません...
ご指摘の通り、Port 8883(MQTT over SSL)と, 443(HTTPS)のアウトバンド接続が許可されているネットワーク環境が必要となります。

**Comment by hanakooota** [comment]
回答ありがとうございました。
