### ISSUE TITLE
Deguが送信したJSONメッセージがモノのシャドウに反映されません

### ISSUE THREAD

**Issue by masaru-fukushima** [open-degu/USER_COMMUNITY#11]
#9 の続きです。
[Deguゲートウェイのセットアップ](
https://open-degu.github.io/user_manual/30_setup/
)の最下段まで設定を完了しましたが、
<img width="300" alt="Degu_AWS_Shadow" src="https://user-images.githubusercontent.com/40412862/56483082-94111c00-6502-11e9-9079-4f34763e1f19.png">
画像の通りシャドウが反映されません。

Deguからは下記メッセージが出力されています。
`Unable to receive packet`

#10 の[返信](
https://github.com/open-degu/USER_COMMUNITY/issues/10#issuecomment-485297985
)を参照してpingを実行した結果は下記の通りです。

```
root@armadillo:~# ping6 -I wpan0 <IP address>
PING <IP address>(<IP address>) from <IP address> wpan0: 56 data bytes
64 bytes from <IP address>: icmp_seq=1 ttl=64 time=16.5 ms
64 bytes from <IP address>: icmp_seq=2 ttl=64 time=22.9 ms
...

--- <IP address> ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 14.590/16.997/22.933/3.031 ms
```

DeguとDeguゲートウェイ間で通信は確立できていそうなのですが、
どうすればシャドウを反映できるでしょうか。

**Comment by takumiando** [comment]
Deguの電源を入れ直しても、AWS IoT Core上のシャドウは更新されませんか?

**Comment by masaru-fukushima** [comment]
はい。
Deguゲートウェイの電源を入れたまま
DeguのUSBケーブルを抜き差ししましたが、更新されませんでした。

抜く前と抜いた後で以下のコマンドの挙動は変わってませんでした。
（DeguはDeguゲートウェイから認識されたままでした。）
```
wpanctl getprop
ping6 -I wpan0 <IP address>
```

**Comment by masaru-fukushima** [comment]
申し訳ございません、ただ今確認したところ、シャドウが更新されていました。

取り急ぎご連絡いたします。
