### ISSUE TITLE
Threads通信のスループットについて

### ISSUE THREAD

**Issue by ghost** [open-degu/USER_COMMUNITY#13]
やりたいことは決まっていないのですが、
Deguの通信でどのような容量のデータまで送れるかを検討しています。

Deguゲートウェイと、センサーユニット間通信の規格上の通信速度は情報ありませんでしょうか。
また、ダミーデータでよいので実際のスループット計測のデータもお持ちの方いらっしゃいましたら、可能であれば教えていただければと思います。

**Comment by ohsawa** [comment]
規格上の帯域は最大で250kbpsになります。

実際にはDeguゲートウェイ1台とDegu複数での接続になるので、
この帯域を複数のDeguが共有することになります。

そのため複数のDeguが同時にパケットを送信すると、個々の
Deguにとってはスループットが低下するように見えます。

また、電子レンジやモーター等で周辺の電波障害が発生している場合や、
濃い霧や雨等で電波が減衰した場合にも再送は頻発するためスループットが
低下する可能性があります。

**Comment by ghost** [comment]
情報ありがとうございました。
参考にさせていただきます。
