### ISSUE TITLE
クラウドから制御

### ISSUE THREAD

**Issue by chikari3110** [open-degu/USER_COMMUNITY#18]
クラウド(AWS)側からDEGUを制御して、たとえばLEDのON/OFFをしたいのですが、サンプルコードあるいは参考となる資料などはございますでしょうか。

**Comment by takumiando** [comment]
次のサンプルコードでは、AWS IoTのDevice ShadowからLEDを制御することができます。

https://github.com/open-degu/degu-micropython-samples/blob/master/basic/control_led/main.py

AWS IoTに登録されているDeguのThingの、Device Shadowにdesiredを記述することで、
Degu本体に実装されているLED2をON/OFFすることができます。

ON:
```
{
  "desired": {
    "led": "ON"
  }
}
```

OFF:
```
{
  "desired": {
    "led": "OFF"
  }
}
```

**Comment by chikari3110** [comment]
shadow操作による制御動作確認できました。
サンプルコードでは一定時間(1秒)のポーリングによりshadowの変化を検出していますが、変化が無い場合でも毎秒AWSIoTの料金が発生することになるのでしょうか？
deltaの変化をcallback関数でリアルタイムに検出する、といった実装はできるのでしょうか？

**Comment by naomitodori** [comment]
回答が遅くなり、申し訳ありません。

仰る通り、上記のサンプルコードでは毎秒shadowをGETしておりますので
その都度AWS IoT Coreの使用回数としてカウントされます。

> deltaの変化をcallback関数でリアルタイムに検出する、といった実装はできるのでしょうか？

現状、delta検出の対応はしておりません。

**Comment by chikari3110** [comment]
承知しました。ご確認ありがとうございました。
