### ISSUE TITLE
DEGU同士の通信

### ISSUE THREAD

**Issue by seekaihatsu** [open-degu/USER_COMMUNITY#20]
DEGU同士でUPD通信させたいのですが、サンプルコードなどはございますでしょうか？
コンソールから $ ot udp コマンドで送受信のほうは確認ができたのですが、pythonコードで書こうとすると受信側の処理がうまくできません。

**Comment by takumiando** [comment]
Degu同士での通信はサポートしておりません。
あるDeguの状態によって別のDeguを操作するためには、Device Shadowを利用するようデザインしております。

**Comment by seekaihatsu** [comment]
承知しました。ありがとうございました。
