### ISSUE TITLE
SDカードにアクセス

### ISSUE THREAD

**Issue by fuutouya** [open-degu/USER_COMMUNITY#22]
deguを使ってAWSにアップするとともに、sdカードにも保存したいと思いっております。
UARTのSDカードのシールド
https://www.switch-science.com/catalog/1292/
を見つけたのですが、参考になるページやサンプルコードなどあれば教えていただきたいのですが、
よろしくお願いします。

**Comment by inmotions** [comment]
Hello，I want to ask a question。After I executed this command：$ sudo dfu-util --alt 1 -D degu.bin。Why is my Tera Term showing one：dfu-util: Could not open file degu.bin for reading: No such file or directory？

**Comment by naomitodori** [comment]
こちらのSDカードシールドですが、GroveコネクタでDeguに接続しての使用を想定されてますでしょうか？

**Comment by fuutouya** [comment]
あまり詳しくないのでのですが、「GroveコネクタUART」に接続してしようできないのかと思っております。

**Comment by naomitodori** [comment]
搭載されているUART GroveコネクタはSDと直接接続されておりませんでした。Arduino用のSDカードシールドとして使用するもののようです。

**Comment by fuutouya** [comment]
ありがとうございます

**Comment by yoshidam-at** [comment]
@fuutouya 
しばらく更新がありませんが、このIssueをCloseしてもいいでしょうか？
7日程何もなければCloseします。
