### ISSUE TITLE
Deguのファームウェアの更新について

### ISSUE THREAD

**Issue by okiwatanabe** [open-degu/USER_COMMUNITY#25]
現在、初めてDeguゲートウェイとベースユニットを使用した設定をマニュアルに従って進めていますが、初心者ゆえに不明な点がありますのでお伺いします。
ファームウェアをダウンロードし回答すると以下の２つのファイルが存在しますが、どちらをDeguに適用したらよろしいでしょうか？
　・degu-router-v0.9.4.bin
　・degu-v0.9.4.bin
よろしくお願いします。

**Comment by naomitodori** [comment]
DeguにRouter機能(Threadネットワーク内のパケットをルーティング)を
持たせたい場合、`degu-router-v0.9.4.bin` を適用してください。

**Comment by jinscafe** [comment]
確認が遅くなり申し訳ございませんでした。
ご回答いただきありがとうございます。

**Comment by yoshidam-at** [comment]
@okiwatanabe, @jinscafe 
しばらく更新がありませんが、このIssueをCloseしてもいいでしょうか？
7日程何もなければCloseします。
