### ISSUE TITLE
UARTに関して

### ISSUE THREAD

**Issue by sasakura5440** [open-degu/USER_COMMUNITY#36]
お世話になります。
DeguベースボードのUARTポートを使用して、センサーからのデータを受信しようとしております。
GPSのサンプルを使用して、初期設定をしようとしております。
質問がございます。
main.pyを_main.pyにし、端末ソフト（１１５２００BPS)でDeguベースボードに入り込み、
upythonを起動後、
>>>from machine import UART
>>> GPS_BAUDRATE = 9600 
>>>uart = UART(0, GPS_BAUDRATE)
後、UARTの設定情報を確認するため、
>>>uart<改行>
と入力しますと
UART(0, baudrate=9600, bits=3, parity=None, stop=1)
が表示されます。
また、
>>>uart.init(9600, bits=8, parity=None, stop=1)
と入力後も
>>>uart<改行>
と入力しますと
UART(0, baudrate=9600, bits=3, parity=None, stop=1)
と表示されます。
bits=3は、データビットが3ビットだという意味でしょうか？
データビットは、８になると考えていますが、何か間違いが有るのでしょうか？

よろしくお願い致します。

**Comment by yoshidam-at** [comment]
bitsに設定できるのは8のみです。
表示上の不具合がある為、表示は3になりますが、設定値は8になっています。

以下のenum値をそのまま表示している状態です。
zephyr/include/drivers/uart.h

    /** @brief Number of data bits. */
    enum uart_config_data_bits {
        UART_CFG_DATA_BITS_5,
        UART_CFG_DATA_BITS_6,
        UART_CFG_DATA_BITS_7,
        UART_CFG_DATA_BITS_8,
        UART_CFG_DATA_BITS_9,
    };

**Comment by sasakura5440** [comment]
有難うございます。
