### ISSUE TITLE
古い型番のゲートウェイを使った開発は可能ですか

### ISSUE THREAD

**Issue by masaru-fukushima** [open-degu/USER_COMMUNITY#6]
https://open-degu.github.io/degu_gw_manual/atmark-techno_degu-gw-g3/

「既にArmadillo-IoT ゲートウェイ G3 M1モデルを持っている場合、Deguゲートウェイ G3と同等の構成にすることができます。」
と書かれていますが、最新モデル以外のゲートウェイを使ってDeguのシステムを開発することは可能でしょうか。

**Comment by takumiando** [comment]
可能ですが、注意点があります。

3G通信モジュール PDS6-Jを搭載しているモデルでは、Linux上でのデバイス名(`/dev/ttyACM0`)が、PDS6-JとThreadアドオンモジュールとで衝突し、うまく動作しません。
この問題については、今後のソフトウェアアップデートにて解決予定です。

PDS6-Jを搭載していないモデルについては、最新のソフトウェアバージョンにて、Deguゲートウェイとして問題なく動作します。

**Comment by ohsawa** [comment]
一応補足します。
「Armadillo-IoT ゲートウェイ G3 であれば」、可能です。
G2、Gの付かない機種では対応することができません、

**Comment by masaru-fukushima** [comment]
ご回答ありがとうございました。
