### ISSUE TITLE
degu-managerがArmadillo-IoT G3にインストールできません

### ISSUE THREAD

**Issue by masaru-fukushima** [open-degu/USER_COMMUNITY#7]
Armadillo-IoT ゲートウェイ G3 開発セット([AGX3020-D00Z](
https://armadillo.atmark-techno.com/armadillo-iot-g3/AGX3020-D00Z
))を
Deguゲートウェイとして利用することを試しています。

上記ゲートウェイを操作して[Deguゲートウェイマニュアル](
https://open-degu.github.io/degu_gw_manual/atmark-techno_degu-gw-g3/
)の
「debianパッケージのインストール」の手順に従ったところ、
下記エラーメッセージが出力されました。

```
root@armadillo:~# apt-get install degu-manager
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package degu-manager
```
LinuxカーネルとDTB(Device Tree Blob)は
[製品アップデートのお知らせ](
https://armadillo.atmark-techno.com/news/20190327/software-update-aiotg3
)から下記をダウンロード、
- uImage-x1-v4.9-at6
- armadillo_iotg_g3-v4.9-at6.dtb

[WinSCP](
https://users.atmark-techno.com/blog/1913/2847
)でゲートウェイにファイルを追加した後、
[イメージファイルの書き換え方法](
https://manual.atmark-techno.com/armadillo-iot-g3/armadillo-iotg-g3_product_manual_ja-2.1.0/ch11.html#sct.update_image_simply.linux
)の手順で書き換えてます。

どうすればエラーメッセージを出力させずに、
degu-managerをインストールできるでしょうか。

**Comment by takumiando** [comment]
debianのバージョンも、Linuxカーネルに合わせてアップデートしていますか?
`uImage-x1-v4.9-at6`に対応するdebianユーザーランドのバージョンは`Stretch`です。`Jessie`のままの場合、`degu-manager`をインストールすることができません。

[Armadillo-IoTゲートウェイ G3でLinux3.14をご利用のお客様へ](https://users.atmark-techno.com/armadillo-iot-g3/software-linux-3-14)

`Jessie`をお使いの場合は、ユーザーランドも`Stretch`へ[アップデートしてください。](https://manual.atmark-techno.com/armadillo-iot-g3/armadillo-iotg-g3_product_manual_ja-2.1.0/ch11.html#sct.update_image_simply.rootfs_debian)

もし`Stretch`をお使いの場合は、`install`する前に`update`しているかどうか確認してください。

```
# apt-get update
# apt-get install degu-manager
```

**Comment by masaru-fukushima** [comment]
> debianのバージョンも、Linuxカーネルに合わせてアップデートしていますか?

していませんでした。

[製品ソフトウェア (Linux 4.9)](
https://users.atmark-techno.com/armadillo-iot-g3/software
)からGNU/Linux 9（Stretch）ユーザーランドをダウンロードして、
[ルートファイルシステムの書き換え](
https://manual.atmark-techno.com/armadillo-iot-g3/armadillo-iotg-g3_product_manual_ja-2.1.0/ch11.html#sct.update_image_simply.rootfs_debian
)たら、degu-managerがインストールできました。

ご回答ありがとうございました。
