### ISSUE TITLE
AWS IoT Coreの「モノ」にDeguのMACアドレスが登録されません

### ISSUE THREAD

**Issue by masaru-fukushima** [open-degu/USER_COMMUNITY#9]
[Deguゲートウェイのセットアップ](
https://open-degu.github.io/user_manual/30_setup/
)の手順に従い、
PC上で"http://(DeguゲートウェイのIPアドレス)/degu/"にアクセスし、
仮のMACアドレス(00112233AABBCCDD)を入力して
登録ボタンを押すと入力欄は空欄になったのですが、
AWS IoT Coreの「モノ」に新規に登録されませんでした。

Deguゲートウェイで下記コマンドを実行したところ、
`root@armadillo:~# ls /etc/coap-mqtt/`
`RootCA.crt  mqttinfo.json`
MQTTINFO.JSONに記載されている"key"と"cert"がなかったのですが、
それが原因でしょうか。あるいは別の手順のミスが原因でしょうか。

**Comment by ohsawa** [comment]
keyとcertが生成されていない場合、次の可能性があります。

1. 起動時にDeguゲートウェイがインターネットに接続できない
1. aws_endpoint,secretaccesskey,accesskeyid,regionの値が誤っている

起動時に何が起きたのか調べるために、Deguゲートウェイのシリアルコンソールに
rootでログインして次のコマンドを実行した結果を教えてください。

` # resize && systemctl status degu-manager`

**Comment by masaru-fukushima** [comment]
実行しました

```
root@armadillo:~# resize && systemctl status degu-manager
COLUMNS=157;
LINES=35;
export COLUMNS LINES;
● degu-manager.service
   Loaded: loaded (/lib/systemd/system/degu-manager.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-04-22 00:16:31 UTC; 42min ago
 Main PID: 2201 (code=exited, status=1/FAILURE)

Apr 22 00:16:31 armadillo degu-manager[2201]:   File "/usr/bin/degu-manager", line 45, in register_gw
Apr 22 00:16:31 armadillo degu-manager[2201]:     resp =  self.iot.create_thing(thingName=name, thingTypeName='Armadillo')
Apr 22 00:16:31 armadillo degu-manager[2201]:   File "/usr/lib/python3/dist-packages/botocore/client.py", line 251, in _api_call
Apr 22 00:16:31 armadillo degu-manager[2201]:     return self._make_api_call(operation_name, kwargs)
Apr 22 00:16:31 armadillo degu-manager[2201]:   File "/usr/lib/python3/dist-packages/botocore/client.py", line 537, in _make_api_call
Apr 22 00:16:31 armadillo degu-manager[2201]:     raise ClientError(parsed_response, operation_name)
Apr 22 00:16:31 armadillo degu-manager[2201]: botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the CreateThing ope
Apr 22 00:16:31 armadillo systemd[1]: degu-manager.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 00:16:31 armadillo systemd[1]: degu-manager.service: Unit entered failed state.
Apr 22 00:16:31 armadillo systemd[1]: degu-manager.service: Failed with result 'exit-code'.
```

**Comment by ohsawa** [comment]
原因がわかりました。
真っ新なアカウントに対して起きるバグです。本日中にアップデートして
apt-get update && apt-get upgradeで更新できるようにリリースするので、
暫くお待ちください。

**Comment by masaru-fukushima** [comment]
ご対応いただき、ありがとうございます。
よろしくお願いします。

**Comment by ohsawa** [comment]
degu-managerを更新しました。
Deguゲートウェイをインターネットに接続した状態で、
root権限で次の手順を実行するとアップデートされます。

`# apt-get update && apt-get upgrade`

**Comment by masaru-fukushima** [comment]
<img width="734" alt="Degu_AWS_Shadow" src="https://user-images.githubusercontent.com/40412862/56482950-d71ebf80-6501-11e9-92e5-93aa2073d86d.png">

登録までできました。ありがとうございました。

JSONメッセージが反映されていない件については改めてIssueを作成します。
